import {useState} from 'react';
import {Link,Navigate,useNavigate} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {ArrowRight,Eye,EyeOff,Check,Mail,BookOpen} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {supabase} from '@/supabaseClient';
import {useAuth} from '@/context/AuthContext';
import {type Course,courseTitle,messageOf} from '@/lib/study';
import {Brand,ErrorState,Loading,Tag} from './shared';
export function AuthPage({signup=false}:{signup?:boolean}){
 const {session,onboarded,refresh}=useAuth(),navigate=useNavigate();
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false),[confirmation,setConfirmation]=useState(false);
 if(session)return <Navigate to={onboarded?'/dashboard':'/onboarding'} replace/>;
 async function submit(event:React.FormEvent<HTMLFormElement>){
  event.preventDefault();if(busy)return;setBusy(true);setError('');const form=new FormData(event.currentTarget);
  try{const email=String(form.get('email')).trim(),password=String(form.get('password'));
   if(signup){const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+'/onboarding',data:{firstName:String(form.get('firstName')).trim(),lastName:String(form.get('lastName')).trim()}}});if(error)throw error;if(!data.session){setConfirmation(true);return;}}
   else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}
   await refresh();navigate(signup?'/onboarding':'/dashboard');
  }catch(e){setError(messageOf(e));}finally{setBusy(false);}
 }
 return <div className="auth-layout"><aside className="auth-story"><Brand/><div><Tag>YOUR NEXT CHAPTER STARTS HERE</Tag><h1>Good questions.<br/>Clearer thinking.<br/><span>Real progress.</span></h1><p>A focused place to work through your course material, one idea at a time.</p><div className="auth-quote"><BookOpen size={25}/><p>Understanding is a process.<br/>Make a little space for it.</p></div></div><span className="small muted">IntuiLearn · Your personal study workspace</span></aside><main className="auth-main"><div className="mobile-brand"><Brand/></div><section className="auth-form-wrap">{confirmation?<><div className="round-icon"><Mail size={28}/></div><h1>Check your inbox.</h1><p className="muted">Open the confirmation link to verify your email. Your next step is choosing your courses.</p><Button asChild variant="outline"><Link to="/login">Back to sign in<ArrowRight size={16}/></Link></Button></>:<><span className="eyebrow">{signup?'LET’S GET YOU SETTLED':'WELCOME BACK'}</span><h1>{signup?'Make this your space.':'Pick up where you left off.'}</h1><p className="muted">{signup?'Create your account. Your study profile comes next.':'Sign in to your courses, questions, and next ideas.'}</p><form onSubmit={submit} className="form-stack">{signup&&<div className="form-row"><div><Label htmlFor="firstName">First name</Label><Input id="firstName" name="firstName" autoComplete="given-name" required maxLength={80}/></div><div><Label htmlFor="lastName">Last name</Label><Input id="lastName" name="lastName" autoComplete="family-name" required maxLength={80}/></div></div>}<div><Label htmlFor="email">Email address</Label><Input id="email" name="email" type="email" autoComplete="email" placeholder="you@university.edu" required/></div><div><Label htmlFor="password">Password</Label><div className="password-field"><Input id="password" name="password" type={show?'text':'password'} autoComplete={signup?'new-password':'current-password'} minLength={signup?8:1} required/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div>{signup&&<p className="field-hint">Use at least 8 characters.</p>}</div>{error&&<ErrorState message={error}/>}<Button type="submit" disabled={busy} className="w-full" size="lg">{busy?'One moment…':signup?'Create account':'Sign in'}<ArrowRight size={17}/></Button></form><p className="auth-switch">{signup?'Already have an account?':'New to IntuiLearn?'} <Link to={signup?'/login':'/signup'}>{signup?'Sign in':'Create an account'}</Link></p></>}</section><Link className="back-home" to="/">← Back to IntuiLearn</Link></main></div>
}
export function Onboarding(){
 const {user,onboarded,refresh}=useAuth(),navigate=useNavigate();const [selected,setSelected]=useState<number[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const courses=useQuery({queryKey:['catalog'],queryFn:async()=>{const {data,error}=await supabase.from('courses').select('*');if(error)throw error;return data as Course[];}});
 if(onboarded)return <Navigate to="/dashboard" replace/>;
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected.length){setError('Choose at least one course to get started.');return;}setBusy(true);setError('');const f=new FormData(event.currentTarget);try{const {error}=await supabase.rpc('complete_onboarding',{major:f.get('major'),academic_year:f.get('year'),study_hours:Number(f.get('hours')),goals:f.get('goals'),course_ids:selected});if(error)throw error;await refresh();navigate('/dashboard');}catch(e){setError(messageOf(e));}finally{setBusy(false);}}
 return <div className="onboarding"><header><Brand/><Tag>Step 2 of 2</Tag></header><main><span className="eyebrow">MAKE YOURSELF AT HOME</span><h1>What are you learning, {user?.fname||'today'}?</h1><p className="muted">A few details to shape your workspace. You can start small.</p><form onSubmit={submit} className="form-stack"><div className="form-row"><div><Label htmlFor="major">Field of study</Label><Input name="major" id="major" placeholder="e.g. Computer Science" required maxLength={100}/></div><div><Label htmlFor="year">Academic year</Label><select id="year" name="year" required defaultValue=""><option value="" disabled>Choose your year</option>{['First year','Second year','Third year','Fourth year','Graduate','Independent learner'].map(x=><option key={x}>{x}</option>)}</select></div></div><fieldset><legend>Your courses</legend><p className="field-hint">Choose where you’d like to begin.</p>{courses.isLoading?<Loading text="Loading available courses…"/>:courses.error?<ErrorState message="We couldn’t load the course catalog." retry={()=>void courses.refetch()}/>:!courses.data?.length?<p className="muted">No courses have been prepared yet. Ask the administrator to load the demo seed.</p>:courses.data.map(c=><label className={`course-choice ${selected.includes(c.course_id)?'selected':''}`} key={c.course_id}><input type="checkbox" checked={selected.includes(c.course_id)} onChange={()=>setSelected(prev=>prev.includes(c.course_id)?prev.filter(x=>x!==c.course_id):[...prev,c.course_id])}/><BookOpen size={21}/><span><strong>{courseTitle(c.course_name)}</strong><small>{c.course_code}</small></span>{selected.includes(c.course_id)&&<Check size={17}/>}</label>)}</fieldset><div className="form-row"><div><Label htmlFor="hours">Weekly study hours</Label><Input id="hours" name="hours" type="number" min={1} max={60} defaultValue={10} required/></div><div><Label htmlFor="goals">Learning goal <span className="muted">(optional)</span></Label><Input id="goals" name="goals" placeholder="What would you like to understand?" maxLength={500}/></div></div>{error&&<ErrorState message={error}/>}<Button disabled={busy||!courses.data?.length} size="lg">{busy?'Preparing your space…':'Enter your workspace'}<ArrowRight size={17}/></Button></form></main></div>
}
