import {Link} from 'react-router-dom';
import {ArrowUpRight,BookOpen,Loader2,AlertCircle,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
export function Brand({compact=false}:{compact?:boolean}){return <Link to="/" className="brand" aria-label="IntuiLearn home"><span className="brand-mark"><BookOpen size={19}/></span>{!compact&&<>intui<span className="brand-light">learn</span><span className="brand-dot">.</span></>}</Link>}
export function Loading({text='Getting your workspace ready…'}:{text?:string}){return <div className="state" role="status"><Loader2 className="animate-spin" size={23}/><p>{text}</p></div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="error-state" role="alert"><AlertCircle size={18}/><div><p>{message}</p>{retry&&<button className="text-link" onClick={retry}><RefreshCw size={13}/>Try again</button>}</div></div>}
export function Empty({title,children}:{title:string;children:React.ReactNode}){return <div className="state empty-state"><BookOpen size={26}/><h3>{title}</h3><p>{children}</p></div>}
export function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
export function Setup(){return <div className="setup-page"><Brand/><section className="auth-card"><Tag>Workspace setup</Tag><h1>A fresh start for<br/>better learning.</h1><p className="muted">This installation is ready to connect to your study services. Your existing project has been left untouched.</p><ol className="setup-steps"><li>Create a fresh Supabase project and apply the schema and demo seed.</li><li>Configure the frontend and backend local environment files using their examples.</li><li>Process the demo course, start the APIs, and restart the frontend.</li></ol><p className="muted small">The root README contains the exact commands. Real accounts and course data become available once setup is complete.</p><Button asChild variant="outline"><Link to="/">Back to IntuiLearn<ArrowUpRight size={16}/></Link></Button></section></div>}
